---
- name: Install latest datadog-agent package (dnf)
  ansible.builtin.dnf:
    name: "{{ datadog_agent_flavor }}"
    update_cache: yes
    state: latest  # noqa 403
  register: datadog_agent_install
  when: not ansible_check_mode and ansible_pkg_mgr == "dnf"
  notify: Restart datadog-agent

- name: Install latest datadog-agent package (yum)
  ansible.builtin.yum:
    name: "{{ datadog_agent_flavor }}"
    update_cache: yes
    state: latest  # noqa 403
  register: datadog_agent_install
  when: not ansible_check_mode and ansible_pkg_mgr == "yum"
  notify: Restart datadog-agent
