---
#
# Ansible managed
#
repository:
  description: Install and configure Datadog on your systems.
  homepage: https://buluma.github.io/
  topics: datadog, ansible, molecule, tox, playbook, hacktoberfest
