---
# handlers file for datadog

- name: restart datadog-agent-sysprobe
  service:
    name: datadog-agent-sysprobe
    state: restarted
  when: datadog_enabled and datadog_sysprobe_enabled and not ansible_check_mode and not ansible_facts.os_family == "Windows" and not ansible_facts.os_family == "Darwin"

- name: restart datadog-agent
  service:
    name: datadog-agent
    state: restarted
  when: datadog_enabled and not ansible_check_mode and not ansible_facts.os_family == "Windows" and not ansible_facts.os_family == "Darwin"

# When needed, our macOS tasks call this handler to require a
# macOS Agent restart (through notify: restart datadog-agent-macos).
# When notified, the below handler is executed at the end of the playbook run.
# The include_tasks loads the handlers/main-macos.yml file, which contains the real service restart task
# and runs it, triggering the macOS Agent restart.
- name: restart datadog-agent-macos
  include_tasks: handlers/main-macos.yml
