---
- name: Unload datadog-agent service
  ansible.builtin.command: "launchctl unload -wF {{ datadog_macos_system_plist_file_path }}"
  become: true
  check_mode: false
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Darwin"
  changed_when: true

- name: Load datadog-agent service
  ansible.builtin.command: "launchctl load -wF {{ datadog_macos_system_plist_file_path }}"
  become: true
  check_mode: false
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Darwin"
  changed_when: true

- name: Restart datadog-agent service
  ansible.builtin.command: "launchctl kickstart -k system/{{ datadog_macos_service_name }}"
  become: true
  register: command_result
  check_mode: false
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Darwin"
  changed_when: true
