---
- name: Restart Windows datadogagent service
  ansible.builtin.win_service:
    name: datadogagent
    state: restarted
    force_dependent_services: true
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Windows"
